name: docker
on: [push]
env:
  TERRAFORM_VERSION: 1.0.7
  TERRAGRUNT_VERSION: 0.34.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Build docker image
        run: docker build --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION --build-arg TERRAGRUNT_VERSION=$TERRAGRUNT_VERSION . --tag terragrunt:$TERRAFORM_VERSION-$TERRAGRUNT_VERSION --tag latest
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image to DockerHub
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/terragrunt
        if: github.ref == 'refs/heads/master'
