name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      opentofu_version:
        description: 'OpenTofu version'
        default: '1.10.6'
      terragrunt_version:
        description: 'Terragrunt version'
        default: '0.87.5'

env:
  DOCKER_REPOSITORY: lcysimon/terragrunt

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          # Determine versions from manual input or env defaults
          OPENTOFU_VERSION=${{ github.event.inputs.opentofu_version || '1.10.6' }}
          TERRAGRUNT_VERSION=${{ github.event.inputs.terragrunt_version || '0.87.5' }}

          echo "Building image with OPENTOFU_VERSION=$OPENTOFU_VERSION and TERRAGRUNT_VERSION=$TERRAGRUNT_VERSION"

          docker build \
            --build-arg OPENTOFU_VERSION=$OPENTOFU_VERSION \
            --build-arg TERRAGRUNT_VERSION=$TERRAGRUNT_VERSION \
            -t ${{ env.DOCKER_REPOSITORY }}:otf$OPENTOFU_VERSION-tg$TERRAGRUNT_VERSION \
            .

      - name: Push Docker image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          OPENTOFU_VERSION=${{ github.event.inputs.opentofu_version || '1.10.6' }}
          TERRAGRUNT_VERSION=${{ github.event.inputs.terragrunt_version || '0.87.5' }}

          docker tag ${{ env.DOCKER_REPOSITORY }}:otf$OPENTOFU_VERSION-tg$TERRAGRUNT_VERSION \
                     ${{ env.DOCKER_REPOSITORY }}:latest

          docker push ${{ env.DOCKER_REPOSITORY }}:otf$OPENTOFU_VERSION-tg$TERRAGRUNT_VERSION
          docker push ${{ env.DOCKER_REPOSITORY }}:latest