name: docker
on: [push]
env:
  DOCKER_REPOSITORY: lcysimon/terragrunt
  TERRAFORM_VERSION: 1.0.10
  TERRAGRUNT_VERSION: 0.35.5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub on main
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push on main
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
            TERRAGRUNT_VERSION=${{ env.TERRAGRUNT_VERSION }}
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:${{ env.TERRAGRUNT_VERSION }}_${{ env.TERRAFORM_VERSION }}
            ${{ env.DOCKER_REPOSITORY }}:latest
