name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REPOSITORY: lcysimon/terragrunt
  OPENTOFU_VERSION: 1.10.6
  TERRAGRUNT_VERSION: 0.87.5

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg OPENTOFU_VERSION=${{ env.OPENTOFU_VERSION }} \
            --build-arg TERRAGRUNT_VERSION=${{ env.TERRAGRUNT_VERSION }} \
            -t ${{ env.DOCKER_REPOSITORY }}:otf${{ env.OPENTOFU_VERSION }}-tg${{ env.TERRAGRUNT_VERSION }} \
            .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag ${{ env.DOCKER_REPOSITORY }}:otf${{ env.OPENTOFU_VERSION }}-tg${{ env.TERRAGRUNT_VERSION }} \
                     ${{ env.DOCKER_REPOSITORY }}:latest
          docker push ${{ env.DOCKER_REPOSITORY }}:otf${{ env.OPENTOFU_VERSION }}-tg${{ env.TERRAGRUNT_VERSION }}
          docker push ${{ env.DOCKER_REPOSITORY }}:latest